export let protoName: string = "AuthProto"

export enum Cmd {
	INVALED = 0,
	eUnameLoginReq = 1,
	eUnameLoginRes = 2,
	eGuestLoginReq = 3,
	eGuestLoginRes = 4,
	eUnameRegistReq = 5,
	eUnameRegistRes = 6,
	ePhoneRegistReq = 7,
	ePhoneRegistRes = 8,
	eGetPhoneRegVerNumReq = 9,
	eGetPhoneRegVerNumRes = 10,
	eBindPhoneNumberReq = 11,
	eBindPhoneNumberRes = 12,
	eResetUserPwdReq = 13,
	eResetUserPwdRes = 14,
	eLoginOutReq = 15,
	eLoginOutRes = 16,
	eEditProfileReq = 17,
	eEditProfileRes = 18,
	eAccountUpgradeReq = 19,
	eAccountUpgradeRes = 20,
	eGetUserCenterInfoReq = 21,
	eGetUserCenterInfoRes = 22,
	eReloginRes = 23,
	eUserLostConnectRes = 24
}

export let CmdName = {
	[0] : "INVALED",
	[1] : "UnameLoginReq",
	[2] : "UnameLoginRes",
	[3] : "GuestLoginReq",
	[4] : "GuestLoginRes",
	[5] : "UnameRegistReq",
	[6] : "UnameRegistRes",
	[7] : "PhoneRegistReq",
	[8] : "PhoneRegistRes",
	[9] : "GetPhoneRegVerNumReq",
	[10] : "GetPhoneRegVerNumRes",
	[11] : "BindPhoneNumberReq",
	[12] : "BindPhoneNumberRes",
	[13] : "ResetUserPwdReq",
	[14] : "ResetUserPwdRes",
	[15] : "LoginOutReq",
	[16] : "LoginOutRes",
	[17] : "EditProfileReq",
	[18] : "EditProfileRes",
	[19] : "AccountUpgradeReq",
	[20] : "AccountUpgradeRes",
	[21] : "GetUserCenterInfoReq",
	[22] : "GetUserCenterInfoRes",
	[23] : "ReloginRes",
	[24] : "UserLostConnectRes",
}